name: gust_template
description: MVC framework for Dart
version: 0.0.1
repository: https://github.com/Parkar99/gust.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mustache_template: ^2.0.0
  path: ^1.8.0
  postgres: ^2.3.1
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0

dev_dependencies:
  lint: ^1.5.3
